package org.pymobile.app;

import android.content.Context;
import android.content.res.ColorStateList;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.text.Editable;
import android.text.InputFilter;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.KeyEvent;
import android.view.MotionEvent;
import android.view.View;
import android.view.ViewConfiguration;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Filter;
import android.widget.FrameLayout;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Dependency-free native views for vector icons/charts, range input and paging. */
final class AdvancedViews {
    private AdvancedViews() {}

    private static int color(String value, int fallback) {
        try { return Color.parseColor(value); }
        catch (IllegalArgumentException error) { return fallback; }
    }

    /** Shared snapping contract, mirrored by RangeSlider._snap(). */
    static final class RangeMath {
        static double snap(double value, double minimum, double maximum, double step) {
            value = Math.max(minimum, Math.min(maximum, value));
            if (value == maximum) return value;
            double result = minimum + Math.floor((value - minimum) / step + 0.5) * step;
            return Math.max(minimum, Math.min(maximum, result));
        }
    }

    /** Renders the JSON primitives generated by drawing.py / charts.py. */
    static final class VectorView extends View {
        final String kind;
        private final boolean button;
        private JSONObject drawing = new JSONObject();
        private String id = "";
        private final Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        private final float density;
        private int desiredSize = 24;
        private int desiredHeight = 220;
        private int defaultColor = Color.DKGRAY;

        VectorView(Context context, String kind) {
            super(context);
            this.kind = kind;
            button = "IconButton".equals(kind);
            density = context.getResources().getDisplayMetrics().density;
            setFocusable(button);
            setClickable(button);
            if (button) {
                GradientDrawable mask = new GradientDrawable();
                mask.setColor(Color.WHITE);
                mask.setCornerRadius(1000);
                setForeground(new RippleDrawable(ColorStateList.valueOf(0x333F51B5), null, mask));
                setOnClickListener(new OnClickListener() {
                    @Override public void onClick(View v) {
                        if (isEnabled()) Native.dispatchEvent(id, "press", "");
                    }
                });
            }
        }

        void bind(String id, JSONObject props, int textColor) {
            this.id = id;
            defaultColor = textColor;
            JSONObject next = props.optJSONObject("drawing");
            drawing = next == null ? new JSONObject() : next;
            desiredSize = props.optInt("size", button ? 48 : 24);
            desiredHeight = props.optInt("height", 220);
            String label = props.optString("label", "");
            setContentDescription(label);
            setImportantForAccessibility(label.isEmpty() && !button
                    ? IMPORTANT_FOR_ACCESSIBILITY_NO : IMPORTANT_FOR_ACCESSIBILITY_YES);
            requestLayout();
            invalidate();
        }

        @Override protected void onMeasure(int widthSpec, int heightSpec) {
            int w = Math.round(("Chart".equals(kind) ? 320 : desiredSize) * density);
            int h = Math.round(("Chart".equals(kind) ? desiredHeight : desiredSize) * density);
            setMeasuredDimension(resolveSize(w, widthSpec), resolveSize(h, heightSpec));
        }

        @Override protected void onDraw(Canvas canvas) {
            super.onDraw(canvas);
            float logicalWidth = (float) drawing.optDouble("width", 24);
            float logicalHeight = (float) drawing.optDouble("height", 24);
            if (logicalWidth <= 0 || logicalHeight <= 0) return;
            float availableWidth = Math.max(0, getWidth() - getPaddingLeft() - getPaddingRight());
            float availableHeight = Math.max(0, getHeight() - getPaddingTop() - getPaddingBottom());
            float scale = Math.min(availableWidth / logicalWidth, availableHeight / logicalHeight);
            if (button) scale = Math.min(scale, density); // always a 24-dp icon inside a large target
            if (scale <= 0) return;
            int saved = canvas.save();
            canvas.translate(getPaddingLeft() + (availableWidth - logicalWidth * scale) / 2,
                    getPaddingTop() + (availableHeight - logicalHeight * scale) / 2);
            canvas.scale(scale, scale);
            JSONArray shapes = drawing.optJSONArray("shapes");
            if (shapes != null) for (int i = 0; i < shapes.length(); i++) {
                JSONObject s = shapes.optJSONObject(i);
                if (s == null) continue;
                paint.reset();
                paint.setAntiAlias(true);
                int c = color(s.optString("color", ""), defaultColor);
                if (!isEnabled()) c = (c & 0x00ffffff) | ((Color.alpha(c) * 100 / 255) << 24);
                paint.setColor(c);
                paint.setStrokeWidth((float) s.optDouble("width", 2));
                paint.setStrokeCap(Paint.Cap.ROUND);
                paint.setStrokeJoin(Paint.Join.ROUND);
                String type = s.optString("type", "");
                float x = (float) s.optDouble("x", 0), y = (float) s.optDouble("y", 0);
                if ("line".equals(type)) {
                    paint.setStyle(Paint.Style.STROKE);
                    JSONArray points = s.optJSONArray("points");
                    Path path = new Path();
                    if (points != null) for (int j = 0; j < points.length(); j++) {
                        JSONArray p = points.optJSONArray(j);
                        if (p == null) continue;
                        float px = (float) p.optDouble(0), py = (float) p.optDouble(1);
                        if (j == 0) path.moveTo(px, py); else path.lineTo(px, py);
                    }
                    canvas.drawPath(path, paint);
                } else if ("rect".equals(type)) {
                    canvas.drawRect(x, y, x + (float) s.optDouble("w"), y + (float) s.optDouble("h"), paint);
                } else if ("circle".equals(type)) {
                    paint.setStyle(s.optBoolean("fill", true) ? Paint.Style.FILL : Paint.Style.STROKE);
                    canvas.drawCircle(x, y, (float) s.optDouble("r"), paint);
                } else if ("sector".equals(type)) {
                    float radius = (float) s.optDouble("r");
                    canvas.drawArc(new RectF(x - radius, y - radius, x + radius, y + radius),
                            (float) s.optDouble("start"), (float) s.optDouble("sweep"), true, paint);
                } else if ("text".equals(type)) {
                    paint.setTextSize((float) s.optDouble("size", 12));
                    String align = s.optString("align", "start");
                    paint.setTextAlign("center".equals(align) ? Paint.Align.CENTER
                            : "end".equals(align) ? Paint.Align.RIGHT : Paint.Align.LEFT);
                    canvas.drawText(s.optString("text", ""), x, y - paint.getFontMetrics().top, paint);
                }
            }
            canvas.restoreToCount(saved);
        }
    }

    /** Case-insensitive substring filtering, rather than Android's prefix-only filter. */
    private static final class SuggestionAdapter extends ArrayAdapter<String> {
        private final List<String> all;
        SuggestionAdapter(Context context, List<String> values) {
            super(context, android.R.layout.simple_dropdown_item_1line, new ArrayList<>(values));
            all = new ArrayList<>(values);
        }
        @Override public Filter getFilter() {
            return new Filter() {
                @Override protected FilterResults performFiltering(CharSequence constraint) {
                    String query = constraint == null ? "" : constraint.toString().toLowerCase(Locale.ROOT);
                    ArrayList<String> matches = new ArrayList<>();
                    for (String option : all) if (option.toLowerCase(Locale.ROOT).contains(query)) matches.add(option);
                    FilterResults result = new FilterResults();
                    result.values = matches;
                    result.count = matches.size();
                    return result;
                }
                @SuppressWarnings("unchecked")
                @Override protected void publishResults(CharSequence constraint, FilterResults results) {
                    setNotifyOnChange(false);
                    clear();
                    addAll((List<String>) results.values);
                    notifyDataSetChanged();
                }
                @Override public CharSequence convertResultToString(Object resultValue) {
                    return String.valueOf(resultValue);
                }
            };
        }
    }

    static final class AutoInput extends AutoCompleteTextView {
        private String id = "";
        private boolean binding = false;
        private String optionsSignature = "";
        private int revision = -1;

        AutoInput(Context context) {
            super(context);
            addTextChangedListener(new TextWatcher() {
                @Override public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
                @Override public void onTextChanged(CharSequence s, int start, int before, int count) {
                    if (!binding && isEnabled()) Native.dispatchEvent(id, "change", s.toString());
                }
                @Override public void afterTextChanged(Editable s) {}
            });
            setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override public void onItemClick(AdapterView<?> parent, View view, int position, long rowId) {
                    if (!binding && isEnabled()) Native.dispatchEvent(id, "select", String.valueOf(parent.getItemAtPosition(position)));
                }
            });
        }

        void bind(String id, JSONObject props, int textColor, int hintColor) {
            this.id = id;
            binding = true;
            try {
                setTextColor(textColor);
                setHintTextColor(hintColor);
                setHint(props.optString("placeholder", ""));
                setThreshold(props.optInt("threshold", 1));
                int inputType = InputType.TYPE_CLASS_TEXT;
                if (props.optBoolean("password", false)) inputType |= InputType.TYPE_TEXT_VARIATION_PASSWORD;
                else if (props.optBoolean("multiline", false)) inputType |= InputType.TYPE_TEXT_FLAG_MULTI_LINE;
                if (getInputType() != inputType) setInputType(inputType);
                int maximum = props.optInt("max_length", 0);
                setFilters(maximum > 0 ? new InputFilter[]{new InputFilter.LengthFilter(maximum)} : new InputFilter[0]);
                JSONArray options = props.optJSONArray("options");
                String signature = options == null ? "[]" : options.toString();
                if (!signature.equals(optionsSignature)) {
                    ArrayList<String> values = new ArrayList<>();
                    if (options != null) for (int i = 0; i < options.length(); i++) values.add(options.optString(i));
                    setAdapter(new SuggestionAdapter(getContext(), values));
                    optionsSignature = signature;
                }
                String value = props.optString("value", "");
                int nextRevision = props.optInt("revision", 0);
                if ((!hasFocus() || revision != nextRevision) && !value.contentEquals(getText())) {
                    int caret = getSelectionStart();
                    setText(value, false);
                    setSelection(Math.max(0, Math.min(caret, value.length())));
                }
                revision = nextRevision;
            } finally { binding = false; }
        }
    }

    /** Two actual thumbs on one track, with touch and keyboard input. */
    static final class RangeView extends View {
        private final Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        private final float density;
        private String id = "", label = "Range";
        private double minimum, maximum = 100, step = 1, low, high = 100;
        private int primary = Color.BLUE, text = Color.DKGRAY;
        private int active = 0;
        private boolean dragging;

        RangeView(Context context) {
            super(context);
            density = context.getResources().getDisplayMetrics().density;
            setFocusable(true);
            setClickable(true);
        }
        void bind(String id, JSONObject props, int primary, int text) {
            this.id = id;
            this.primary = primary;
            this.text = text;
            minimum = props.optDouble("minimum", 0);
            maximum = props.optDouble("maximum", 100);
            step = props.optDouble("step", 1);
            low = props.optDouble("low", minimum);
            high = props.optDouble("high", maximum);
            label = props.optString("label", "Range");
            description();
            invalidate();
        }
        private void description() {
            setContentDescription(label + ": " + low + " – " + high + ". " + minimum + " – " + maximum);
        }
        @Override protected void onMeasure(int w, int h) {
            setMeasuredDimension(resolveSize((int) (300 * density), w), resolveSize((int) (64 * density), h));
        }
        private float startX() { return getPaddingLeft() + 20 * density; }
        private float endX() { return Math.max(startX() + 1, getWidth() - getPaddingRight() - 20 * density); }
        private float x(double value) { return startX() + (float) ((value - minimum) / (maximum - minimum)) * (endX() - startX()); }
        @Override protected void onDraw(Canvas canvas) {
            super.onDraw(canvas);
            float y = getPaddingTop() + 25 * density;
            paint.setStrokeWidth(4 * density);
            paint.setStrokeCap(Paint.Cap.ROUND);
            paint.setColor(text); paint.setAlpha(isEnabled() ? 60 : 30);
            canvas.drawLine(startX(), y, endX(), y, paint);
            paint.setColor(primary); paint.setAlpha(isEnabled() ? 255 : 100);
            canvas.drawLine(x(low), y, x(high), y, paint);
            canvas.drawCircle(x(low), y, 9 * density, paint);
            canvas.drawCircle(x(high), y, 9 * density, paint);
            if (hasFocus()) {
                paint.setStyle(Paint.Style.STROKE); paint.setStrokeWidth(2 * density);
                canvas.drawCircle(x(active == 0 ? low : high), y, 13 * density, paint);
                paint.setStyle(Paint.Style.FILL);
            }
            paint.setColor(text); paint.setAlpha(isEnabled() ? 255 : 100);
            paint.setTextSize(12 * getResources().getDisplayMetrics().scaledDensity);
            paint.setTextAlign(Paint.Align.CENTER);
            String values = String.format(Locale.ROOT, "%s – %s", low, high);
            canvas.drawText(values, getWidth() / 2f, getPaddingTop() + 53 * density, paint);
        }
        private void move(float touchX) {
            double value = minimum + Math.max(0, Math.min(1, (touchX - startX()) / (endX() - startX()))) * (maximum - minimum);
            value = RangeMath.snap(value, minimum, maximum, step);
            if (active == 0) low = Math.min(high, value); else high = Math.max(low, value);
            description(); invalidate();
        }
        private void commit() {
            try { Native.dispatchEvent(id, "change", new JSONArray().put(low).put(high).toString()); }
            catch (JSONException ignored) { /* Python guards finite bounds. */ }
        }
        @Override public boolean onTouchEvent(MotionEvent event) {
            if (!isEnabled()) return false;
            switch (event.getActionMasked()) {
                case MotionEvent.ACTION_DOWN:
                    float dl = Math.abs(event.getX() - x(low)), dh = Math.abs(event.getX() - x(high));
                    active = dl < dh || (dl == dh && event.getX() <= x(low)) ? 0 : 1;
                    dragging = true;
                    getParent().requestDisallowInterceptTouchEvent(true);
                    requestFocus(); move(event.getX()); return true;
                case MotionEvent.ACTION_MOVE:
                    if (dragging) move(event.getX()); return true;
                case MotionEvent.ACTION_UP:
                    dragging = false; move(event.getX()); commit(); performClick(); return true;
                case MotionEvent.ACTION_CANCEL:
                    dragging = false; commit(); return true;
                default: return super.onTouchEvent(event);
            }
        }
        @Override public boolean performClick() { return super.performClick(); }
        @Override public boolean onKeyDown(int keyCode, KeyEvent event) {
            if (!isEnabled()) return false;
            if (keyCode == KeyEvent.KEYCODE_DPAD_UP || keyCode == KeyEvent.KEYCODE_DPAD_DOWN) {
                active = keyCode == KeyEvent.KEYCODE_DPAD_UP ? 1 : 0; invalidate(); return true;
            }
            if (keyCode == KeyEvent.KEYCODE_DPAD_LEFT || keyCode == KeyEvent.KEYCODE_DPAD_RIGHT) {
                double delta = keyCode == KeyEvent.KEYCODE_DPAD_RIGHT ? step : -step;
                if (active == 0) low = Math.min(high, RangeMath.snap(low + delta, minimum, maximum, step));
                else high = Math.max(low, RangeMath.snap(high + delta, minimum, maximum, step));
                description(); invalidate(); commit(); return true;
            }
            return super.onKeyDown(keyCode, event);
        }
    }

    /**
     * Star rating input drawn by hand.
     *
     * The platform RatingBar tiles a fixed-size star bitmap and stretches its
     * progress clip with the view's width. In a Column (which stretches its
     * children) or with more stars than fit on the screen, the stars and the
     * filled area stopped lining up: tapping the 8th of 10 stars painted the
     * 9th one partly. Here every star is drawn at the same computed size from
     * the same left edge that touch handling uses, so they cannot disagree.
     */
    static final class StarView extends View {
        private final Paint paint = new Paint(Paint.ANTI_ALIAS_FLAG);
        private final Path star = new Path();
        private final float density;
        private String id = "";
        private int maximum = 5;
        private float rating;
        private int primary = Color.BLUE, text = Color.DKGRAY;
        private int committed;
        private boolean dragging;

        StarView(Context context) {
            super(context);
            density = context.getResources().getDisplayMetrics().density;
            setFocusable(true);
            setClickable(true);
        }
        void bind(String id, JSONObject props, int primary, int text) {
            this.id = id;
            this.primary = primary;
            this.text = text;
            maximum = Math.max(1, props.optInt("maximum", 5));
            if (!dragging) {
                rating = (float) Math.max(0, Math.min(maximum, props.optDouble("rating", 0)));
            }
            description();
            requestLayout();
            invalidate();
        }
        private void description() {
            setContentDescription(String.format(Locale.ROOT, "Rating: %s of %d",
                    rating == Math.rint(rating) ? String.valueOf((int) rating) : String.valueOf(rating),
                    maximum));
        }
        private float maxStar() { return 40 * density; }
        private float starSize() {
            float room = getWidth() - getPaddingLeft() - getPaddingRight();
            return Math.max(1f, Math.min(maxStar(), room / maximum));
        }
        @Override protected void onMeasure(int w, int h) {
            int desiredW = (int) Math.ceil(maxStar() * maximum) + getPaddingLeft() + getPaddingRight();
            int desiredH = (int) Math.ceil(maxStar()) + getPaddingTop() + getPaddingBottom();
            setMeasuredDimension(resolveSize(desiredW, w), resolveSize(desiredH, h));
        }
        private void buildStar(float cx, float cy, float r) {
            star.reset();
            for (int i = 0; i < 10; i++) {
                double angle = -Math.PI / 2 + i * Math.PI / 5;
                float radius = i % 2 == 0 ? r : r * 0.45f;
                float x = cx + (float) (radius * Math.cos(angle));
                float y = cy + (float) (radius * Math.sin(angle));
                if (i == 0) star.moveTo(x, y); else star.lineTo(x, y);
            }
            star.close();
        }
        @Override protected void onDraw(Canvas canvas) {
            super.onDraw(canvas);
            float size = starSize();
            float left = getPaddingLeft();
            float cy = getPaddingTop() + (getHeight() - getPaddingTop() - getPaddingBottom()) / 2f;
            paint.setStyle(Paint.Style.FILL);
            for (int i = 0; i < maximum; i++) {
                float x0 = left + i * size;
                buildStar(x0 + size / 2f, cy, size * 0.46f);
                paint.setColor(text);
                paint.setAlpha(isEnabled() ? 50 : 25);
                canvas.drawPath(star, paint);
                float fill = Math.max(0f, Math.min(1f, rating - i));
                if (fill > 0f) {
                    canvas.save();
                    canvas.clipRect(x0, 0, x0 + size * fill, getHeight());
                    paint.setColor(primary);
                    paint.setAlpha(isEnabled() ? 255 : 110);
                    canvas.drawPath(star, paint);
                    canvas.restore();
                }
            }
            if (hasFocus()) {
                paint.setStyle(Paint.Style.STROKE);
                paint.setStrokeWidth(2 * density);
                paint.setColor(primary);
                canvas.drawRect(left, cy - size / 2f, left + size * maximum, cy + size / 2f, paint);
                paint.setStyle(Paint.Style.FILL);
            }
        }
        private int starAt(float touchX) {
            int value = (int) Math.ceil((touchX - getPaddingLeft()) / starSize());
            return Math.max(1, Math.min(maximum, value));
        }
        private void set(int value) {
            rating = value;
            description();
            invalidate();
        }
        private void commit() {
            int value = Math.round(rating);
            if (value == committed) return;
            committed = value;
            Native.dispatchEvent(id, "change", String.valueOf((float) value));
        }
        @Override public boolean onTouchEvent(MotionEvent event) {
            if (!isEnabled()) return false;
            switch (event.getActionMasked()) {
                case MotionEvent.ACTION_DOWN:
                    committed = Math.round(rating);
                    dragging = true;
                    getParent().requestDisallowInterceptTouchEvent(true);
                    requestFocus(); set(starAt(event.getX())); return true;
                case MotionEvent.ACTION_MOVE:
                    if (dragging) set(starAt(event.getX())); return true;
                case MotionEvent.ACTION_UP:
                    dragging = false; set(starAt(event.getX())); commit(); performClick(); return true;
                case MotionEvent.ACTION_CANCEL:
                    dragging = false; set(committed); return true;
                default: return super.onTouchEvent(event);
            }
        }
        @Override public boolean performClick() { return super.performClick(); }
        @Override public boolean onKeyDown(int keyCode, KeyEvent event) {
            if (!isEnabled()) return false;
            if (keyCode == KeyEvent.KEYCODE_DPAD_LEFT || keyCode == KeyEvent.KEYCODE_DPAD_RIGHT) {
                committed = Math.round(rating);
                int next = Math.round(rating) + (keyCode == KeyEvent.KEYCODE_DPAD_RIGHT ? 1 : -1);
                set(Math.max(0, Math.min(maximum, next)));
                commit();
                return true;
            }
            return super.onKeyDown(keyCode, event);
        }
    }

    /** A one-page-at-a-time container that intercepts only horizontal drags. */
    static final class PagerView extends FrameLayout {
        private String id = "";
        private int index, count = 1;
        private boolean loop, dragging;
        private float downX, downY;
        private final int slop;

        PagerView(Context context) {
            super(context);
            slop = ViewConfiguration.get(context).getScaledTouchSlop();
            setFocusable(true);
            setClickable(true);
            setClipChildren(true);
        }
        void bind(String id, JSONObject props) {
            this.id = id;
            index = props.optInt("value", 0);
            count = props.optInt("item_count", 1);
            loop = props.optBoolean("loop", false);
            setContentDescription("Page " + (index + 1) + " of " + count);
        }
        private void begin(MotionEvent event) { downX = event.getX(); downY = event.getY(); dragging = false; }
        @Override public boolean onInterceptTouchEvent(MotionEvent event) {
            if (!isEnabled()) return false;
            if (event.getActionMasked() == MotionEvent.ACTION_DOWN) begin(event);
            if (event.getActionMasked() == MotionEvent.ACTION_MOVE &&
                    Math.abs(event.getX() - downX) > slop &&
                    Math.abs(event.getX() - downX) > Math.abs(event.getY() - downY) * 1.3f) {
                dragging = true;
                getParent().requestDisallowInterceptTouchEvent(true);
                return true;
            }
            return dragging;
        }
        private void select(int delta) {
            int target = index + delta;
            if (loop) target = (target + count) % count;
            if (target >= 0 && target < count && target != index) Native.dispatchEvent(id, "change", String.valueOf(target));
        }
        @Override public boolean onTouchEvent(MotionEvent event) {
            if (!isEnabled()) return false;
            switch (event.getActionMasked()) {
                case MotionEvent.ACTION_DOWN: begin(event); return true;
                case MotionEvent.ACTION_MOVE:
                    if (dragging && getChildCount() > 0) getChildAt(0).setTranslationX((event.getX() - downX) * 0.4f);
                    return true;
                case MotionEvent.ACTION_UP:
                    if (dragging && Math.abs(event.getX() - downX) > Math.max(slop * 3, getWidth() * 0.15f))
                        select(event.getX() < downX ? 1 : -1);
                    else performClick();
                    // fall through to restore the page on a short/cancelled drag
                case MotionEvent.ACTION_CANCEL:
                    dragging = false;
                    if (getChildCount() > 0) getChildAt(0).animate().translationX(0).setDuration(120).start();
                    return true;
                default: return super.onTouchEvent(event);
            }
        }
        @Override public boolean performClick() { return super.performClick(); }
        @Override public boolean onKeyDown(int code, KeyEvent event) {
            if (isEnabled() && (code == KeyEvent.KEYCODE_DPAD_LEFT || code == KeyEvent.KEYCODE_DPAD_RIGHT)) {
                select(code == KeyEvent.KEYCODE_DPAD_RIGHT ? 1 : -1); return true;
            }
            return super.onKeyDown(code, event);
        }
    }
}
